# Generated by Django 2.2.8 on 2019-12-13 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_dashboardpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turbine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('good', 'Good'), ('error', 'Error'), ('offline', 'Offline')], max_length=7)),
            ],
        ),
    ]
