# Generated by Django 2.2.8 on 2019-12-13 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_getstatuspage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnomalyEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Audio')),
            ],
        ),
    ]
