# Generated by Django 2.2.8 on 2019-12-13 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_anomalyevents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
